on:
  schedule:
    - cron:  '0 7 * * 1'
    # scheduled at 07:00 every Monday

  workflow_dispatch:  # click the button on Github repo!


jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Use Java8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.1.6352462" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Build release apk
      run: ./gradlew :app:assembleFullRelease --stacktrace
    
    - name: List files build
      run: |
        cd app/build/outputs
        ls -LR

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/full/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"

    - uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v2.8.2
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        commitish: master
    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.sign_app.outputs.signedReleaseFile }}
        asset_name: app-full-release-signed.apk
        asset_content_type: application/zip
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.API_KEY_PUSH }}
        MESSAGE: "New build is available of Android APS, click the link for download"
        TITLE: "A New Android APS"
        LINK: ${{ steps.upload_release_asset.outputs.browser_download_url}}
